# Generated by Django 3.1.7 on 2021-04-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketPrice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('customerName', models.CharField(max_length=50)),
                ('creationDate', models.DateField(auto_now=True)),
                ('perfomanceTitle', models.CharField(max_length=100)),
                ('perfomanceTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
